### ISSUE TITLE
Class cast error in result display

### ISSUE THREAD

**Issue by donenrique24** [CWFC-CCFB/CAT#30]
There is a bug when the user select a different graph to display: 

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: repicea.stats.estimates.GaussianEstimate cannot be cast to repicea.stats.estimates.MonteCarloEstimate
	at lerfob.carbonbalancetool.CATUtilityMaps$MonteCarloEstimateMap.mergeWith(CATUtilityMaps.java:260)
	at lerfob.carbonbalancetool.CATUtilityMaps$SpeciesMonteCarloEstimateMap.getSumAcrossSpecies(CATUtilityMaps.java:312)
	at lerfob.carbonbalancetool.CATResultLogGradesPanel.createChart(CATResultLogGradesPanel.java:72)
	at lerfob.carbonbalancetool.CATResultPanel.refreshInterface(CATResultPanel.java:108)
	at repicea.gui.REpiceaPanel.ancestorAdded(REpiceaPanel.java:53)
	at javax.swing.AncestorNotifier.fireAncestorAdded(AncestorNotifier.java:86)
	at javax.swing.AncestorNotifier.propertyChange(AncestorNotifier.java:223)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8448)
	at javax.swing.JComponent.addNotify(JComponent.java:4744)
	at java.awt.Container.addImpl(Container.java:1124)
	at javax.swing.JViewport.setView(JViewport.java:962)
	at lerfob.carbonbalancetool.CATSingleViewPanel.refreshInterface(CATSingleViewPanel.java:78)
	at lerfob.carbonbalancetool.CATSingleViewPanel.itemStateChanged(CATSingleViewPanel.java:90)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1225)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1273)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1328)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:578)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:868)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3318)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:517)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by donenrique24** [comment]
This error ;ight be due to an empty stand at some point in the simulation.

**Comment by donenrique24** [comment]
This is not due to empty stand in the simulation. The simulation with the file UAF6152_MS2_EvenAged10years.csv reproduces the bug.

**Comment by donenrique24** [comment]
The map returned by the method CATSimulationResult.getLogGradePerHa() returns MonteCarloEstimate with different numbers of  realizations. When summing the volume accross the species, the MonteCarloEstimate instances cannot be merged, which results in a GaussianEstimate instance. This behaviour should be checked with previous versions of CAT.

**Comment by donenrique24** [comment]
All the trees from all the realizations are now scanned to set the list of species in the CATCompartmentManager.init method.
